### PR TITLE
v2.0.2

### PR DESCRIPTION
**Pull request by racztiborzoltan**
- v2.0.2
- readme for v2.0.2

### CODE REVIEW

**Comment by gsouf** [comment]
There is almost no change with version 2.0.1, is it ok ?

**Comment by racztiborzoltan** [comment]
Very good question!

My pull request contains the following files:
https://github.com/phalcon/phalcon-devtools/tree/2.0.x/ide/2.0.2/Phalcon

But there are API changes in the changelog:
https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.2
For example:
- added new method: \Phalcon\Text::reduceSlashes()
- added new method: \Phalcon\Text::concat()

I downloaded and install Phalcon v2.0.2 in PHP and generated new ide stub files.
But even so there was no significant difference between files.

I have used the git tags v2.0.2 in phalcon-dev and cphalcon repository.

Interesting!
Perhaps I was too quick?
We wait for a while?

**Comment by gsouf** [comment]
I checked about concat method.

It is in the `devtools 2.0.2` : https://github.com/phalcon/phalcon-devtools/blob/2.0.x/ide/2.0.2/Phalcon/Text.php#L132

but not in the `phalcon stub 2.0.1` : https://github.com/gsouf/phalcon-stubs/blob/master/Phalcon/Text.php

Maybe did you forget something in the commit, or when you copyed files ?

Do you have some time to modify your PR ?

**Comment by racztiborzoltan** [comment]
PR was modified.

Sorry! Apparently I'm distracted. Thank you!
That's all right?

**Comment by gsouf** [comment]
Yes ! Thanks you ! :)

**Pull request merged**
